/*1*/

SELECT NOMEM
FROM TEMPLE
WHERE NUMDE = 121

/*2*/

SELECT *
FROM TEMPLE
WHERE NUMDE = 121

SELECT NOMEM, SALAR
FROM TEMPLE
WHERE NUMHI >3
ORDER BY NOMEM

SELECT COMIS, NUMDE, NOMEM
FROM TEMPLE
WHERE SALAR < 1900
ORDER BY NUMDE, COMIS DESC

SELECT COMIS AS COMISION, NUMDE AS DEPTO, NOMEM AS EMPLEADO
FROM TEMPLE
WHERE SALAR < 1900
ORDER BY NUMDE, COMIS DESC

SELECT NOMDE
FROM TDEPTO
WHERE PRESU > 20

SELECT distinct NUMDE
from temple
where salar < 2500

select distinct comis
from temple
where numde = 110

select salar,comis
from temple
where numde = 111
order by salar, comis

select nomem
from temple
where comis> salar*0.5
order by nomem

select nomem, numhi, salar + numhi*30 as TOTAL
from temple
where numhi >= 4
order by nomem

SELECT CONCAT('DEPARTAMENTO DE ', NOMDE) AS NOMBRE
FROM TDEPTO
WHERE PRESU < 30
ORDER BY NOMDE

SELECT NOMDE,PRESU/12 AS MEDIA, PRESU + 9 AS PRESU_TOTAL
FROM TDEPTO
WHERE PRESU/12 > 3
ORDER BY NOMDE

SELECT NOMEM, SALAR, SALAR * 1.06 AS PRIMER_AÑO, SALAR * 1.12 AS SEGUNDO_AÑO, SALAR * 1.18 AS TERCER_AÑO
FROM TEMPLE
WHERE NUMHI > 4
ORDER BY NOMEM

SELECT NOMEM
FROM TEMPLE
WHERE 60*NUMHI<SALAR*0.1
ORDER BY NOMEM

SELECT NOMEM, SALAR + COALESCE(COMIS,0) AS TOTAL
FROM TEMPLE
WHERE NUMDE = 112
ORDER BY TOTAL DESC, NOMEM

SELECT NOMEM, SALAR + COALESCE(COMIS, 0) AS SAL_TOTAL
FROM TEMPLE
WHERE SALAR + COALESCE(COMIS, 0)> 1800
ORDER BY NUMEM

SELECT DISTINCT NUMDE
FROM TEMPLE
WHERE COALESCE(COMIS, 0)> SALAR * 0.2
ORDER BY NUMDE

/*10*/
SELECT NOMEM FROM TEMPLE
WHERE SALAR < 4* (SELECT MIN(COMIS) FROM TEMPLE)
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE SALAR BETWEEN 2500 AND 3000
ORDER BY NOMEM

SELECT NOMEM, SALAR
FROM TEMPLE
WHERE NUMHI>0 AND (SALAR/NUMHI<1200 OR SALAR/NUMHI>2*COMIS)
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE 'MORA%'
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE '%VALERIANA'
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE '_______,%'
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE '______%,%'
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE '___,%' OR NOMEM LIKE '__,%' OR NOMEM LIKE '_,%'
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE '%EZ, ___%O'
ORDER BY NOMEM

SELECT NOMEM, SALAR*0.1 AS CUANTIA
FROM TEMPLE
WHERE FECNA LIKE '24/04/%' OR FECNA LIKE '30/09/%' OR FECNA LIKE '20/10/%' OR FECNA LIKE '21/11/%'

SELECT NOMEM FROM TEMPLE
WHERE NUMDE = SOME(SELECT NUMDE FROM TEMPLE WHERE NOMEM LIKE 'GALVEZ, PILAR' OR NOMEM LIKE 'FLOR, DOROTEA')
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE SALAR = SOME(SELECT SALAR FROM TEMPLE WHERE NUMDE = 100) AND NUMDE<>100
ORDER BY NOMEM

SELECT NOMEM FROM TEMPLE
WHERE SALAR IN (SELECT SALAR FROM TEMPLE WHERE NUMDE = 100) AND NUMDE<>100
ORDER BY NOMEM

SELECT NOMCE FROM TCENTR
WHERE EXISTS(SELECT SEÑAS FROM TCENTR WHERE SEÑAS LIKE 'C.ATOCHA%')

SELECT NOMEM, SALAR FROM TEMPLE
WHERE EXISTS(SELECT * FROM TEMPLE WHERE NUMDE = 111 AND COMIS>SALAR*0.15) AND NUMDE = 111 AND COMIS IS NOT NULL
ORDER BY NOMEM

SELECT NOMEM, COMIS FROM TEMPLE
WHERE NUMDE = 110 AND EXISTS(SELECT * FROM TEMPLE WHERE COMIS IS NOT NULL)
ORDER BY NOMEM

SELECT NOMEM, SALAR, FECIN FROM TEMPLE
WHERE (FECIN < '01/01/88' AND SALAR < 2000) OR (FECIN > '01/01/88' AND SALAR > 2000)
ORDER BY FECIN, NOMEM

SELECT NOMDE FROM TDEPTO
WHERE NOMDE NOT LIKE 'DIRECCION%' AND NOMDE NOT LIKE 'SECTOR%'
ORDER BY NOMDE

SELECT NOMEM, SALAR, NUMHI
FROM TEMPLE
WHERE (NUMHI=0 AND SALAR>2000) OR (NUMHI>0 AND SALAR<3000)
ORDER BY NOMEM

SELECT NOMEM, NUMDE, SALAR, NUMHI, COMIS FROM TEMPLE
WHERE (NUMDE IN(110,111) AND (NUMHI=0 OR (NUMHI>0 AND SALAR/NUMHI>1000))) OR (NUMDE IN(111,112) AND COMIS IS NULL)

SELECT * FROM TDEPTO
WHERE TIDIR = 'F' OR (TIDIR = 'P' AND PRESU>50) OR (DEPDE IS NULL)
